### ISSUE TITLE
docker composite example

### ISSUE THREAD

**Issue by cpuwolf** [idootop/mi-gpt#279]
```yaml
services:
  mi-gpt:
    image: idootop/mi-gpt:latest
    container_name: mi-gpt
    env_file:
      - /var/snap/docker/common/var-lib-docker/volumes/mi-gpt/.env
    volumes:
      - /var/snap/docker/common/var-lib-docker/volumes/mi-gpt/.migpt.js:/app/.migpt.js
    restart: unless-stopped
```
