### ISSUE TITLE
群晖docker 有安装教程吗

### ISSUE THREAD

**Issue by Jashon** [idootop/mi-gpt#41]

**Comment by idootop** [comment]
我没用过群晖。之前有人在群晖上部署过，成功了的兄弟可以分享下教程。

**Comment by netdog2019** [comment]
同求~~

**Comment by siseboy** [comment]
```yaml
services:
  mi-gpt:
    image: idootop/mi-gpt:latest
    container_name: mi-gpt
    network_mode: bridge
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    env_file:
      - /volume1/docker/xiaomi/.env
    volumes:
      - /volume1/docker/xiaomi/.migpt.js:/app/.migpt.js
```

volumes 根据自己路径来填写，不过是远程部署的，晚上回去语音看看成不成功，看日志的话，小孩中午使用小爱的时候有看到问答。

![image](https://github.com/idootop/mi-gpt/assets/21329989/7ec60a41-7a8f-49a0-b57e-6e5292ec8025)
